version: '3.5'
services:
  db:
    container_name: postgresdb
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - "db:/var/lib/postgresql/data"
      - "./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_database.sql"
  app:
    container_name: cashier-service
    build:
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    depends_on:
      - db
volumes:
  db:
    driver: local